#!/bin/bash

# One-click deployment script for QuickChat Embedding Demo
echo "🚀 Starting QuickChat Embedding Demo deployment..."

# Check for custom allowed domains
ALLOWED_DOMAINS=${1:-"http://localhost:3000,https://localhost:3000"}
echo "📋 Using allowed domains: $ALLOWED_DOMAINS"

# Check if CDK is installed
if ! command -v cdk &> /dev/null; then
    echo "❌ AWS CDK not found. Installing..."
    npm install -g aws-cdk
fi

# Install dependencies
echo "📦 Installing dependencies..."
npm install

# Install ts-node if not present
if ! npm list ts-node &> /dev/null; then
    echo "📦 Installing ts-node..."
    npm install ts-node
fi

# Check AWS credentials and permissions
echo "🔐 Checking AWS credentials..."
aws sts get-caller-identity > /dev/null
if [ $? -ne 0 ]; then
    echo "❌ AWS credentials not configured. Please run 'aws configure' first."
    exit 1
fi

# Bootstrap CDK (if not already done)
echo "🔧 Bootstrapping CDK..."
cdk bootstrap

# Deploy the stack with custom domains
echo "🚀 Deploying infrastructure..."
echo "📋 This will:"
echo "   - Auto-discover Identity Center instance ARN"
echo "   - Create Lambda layer with Python dependencies"
echo "   - Deploy CloudFormation stack with all resources"
echo "   - Configure allowed domains: $ALLOWED_DOMAINS"
echo ""

cdk deploy --require-approval never --context allowedDomains="$ALLOWED_DOMAINS"

# Check if deployment succeeded
if [ $? -ne 0 ]; then
    echo ""
    echo "❌ Deployment failed!"
    echo "Please check the error messages above and try again."
    exit 1
fi

echo ""
echo "✅ Deployment complete!"
echo "📋 Check the outputs above for:"
echo "   - API Gateway URL"
echo "   - Identity Center Instance ARN (auto-discovered)"
echo "   - Lambda Layer ARN"
echo "   - Allowed Domains: $ALLOWED_DOMAINS"
echo ""
echo "🎯 Generating frontend environment file..."

# Get outputs from CloudFormation stack
STACK_NAME="QuickChatEmbeddingStack"
API_ENDPOINT=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='ApiEndpoint'].OutputValue" --output text)
USER_POOL_ID=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='UserPoolId'].OutputValue" --output text)
CLIENT_ID=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='UserPoolClientId'].OutputValue" --output text)
COGNITO_DOMAIN=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='CognitoDomain'].OutputValue" --output text)
AWS_REGION=$(aws configure get region)

# Generate .env.local file with actual values
cat > ../fe/.env.local << EOF
# Auto-generated by deployment script
# QuickChat Embedding Demo Environment Variables

# API Gateway
NEXT_PUBLIC_API_ENDPOINT=${API_ENDPOINT}

# Cognito Configuration
NEXT_PUBLIC_COGNITO_USER_POOL_ID=${USER_POOL_ID}
NEXT_PUBLIC_COGNITO_CLIENT_ID=${CLIENT_ID}
NEXT_PUBLIC_COGNITO_DOMAIN=${COGNITO_DOMAIN}
NEXT_PUBLIC_COGNITO_REDIRECT_URI=http://localhost:3000
NEXT_PUBLIC_COGNITO_RESPONSE_TYPE=token
NEXT_PUBLIC_COGNITO_SCOPE=openid email profile

# QuickSuite Configuration
NEXT_PUBLIC_QUICKSUITE_AGENT_ID=REPLACE_WITH_YOUR_AGENT_ID

# Deployment Configuration
NEXT_PUBLIC_ALLOWED_DOMAINS=${ALLOWED_DOMAINS}
NEXT_PUBLIC_AWS_REGION=${AWS_REGION}

# Generated on: $(date -u +"%Y-%m-%dT%H:%M:%S.%3NZ")
EOF

echo "✅ Generated .env.local file with actual values:"
echo "📋 API Endpoint: ${API_ENDPOINT}"
echo "📋 User Pool ID: ${USER_POOL_ID}"
echo "📋 Client ID: ${CLIENT_ID}"
echo "📋 Cognito Domain: ${COGNITO_DOMAIN}"
echo ""
echo "⚠️  IMPORTANT: Update the QuickSuite Agent ID in fe/.env.local"
echo "   Replace REPLACE_WITH_YOUR_AGENT_ID with your actual agent ID"
echo "   See README.md for steps to get your agent ID from QuickSuite console"

echo ""
echo "🚀 Installing frontend dependencies..."
cd ../fe
npm install

echo ""
echo "✅ Setup complete!"
echo ""
echo "🎯 Next steps:"
echo "   1. Update QuickSuite Agent ID in fe/.env.local (see README.md)"
echo "   2. Create Cognito and Identity Center users (see README.md)"
echo "   3. Start the frontend: cd fe && npm run dev"
echo "   4. Test the embedded chat functionality"
echo ""
echo "💡 To deploy with custom domains:"
echo "   ./deploy.sh 'https://yourdomain.com,https://www.yourdomain.com'"
